name: flutter_parsed_text
description: A Flutter package to parse text and make them into multiple Flutter Text widget.
version: 2.2.1
homepage: https://github.com/fayeed/flutter_parsed_text

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  extended_text: ^9.0.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
