name: flutter_parsed_text
description: A Flutter package to parse text and make them into multiple Flutter Text widget.
version: 3.0.0
homepage: https://github.com/fayeed/flutter_parsed_text

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  extended_text: ^11.1.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
